(part "TS53YL101MR10"
    (packageRef "TS53YL101MR10")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER_") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "72-TS53YL-100")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Sfernice/TS53YL101MR10?qs=MsRaK5qBadT6tnoIaqjVGQ%3D%3D")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "TS53YL101MR10")
    (property "Description" "100 Ohms 0.25W, 1/4W Gull Wing Surface Mount Trimmer Potentiometer Cermet 1.0 Turn Top Adjustment")
    (property "Datasheet_Link" "http://www.vishay.com/docs/51008/ts53.pdf")
    (property "symbolName1" "TS53YL101MR10")
)
